# Generated by Django 5.0.4 on 2025-05-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='atlas_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=100)),
                ('classes', models.CharField(max_length=100)),
                ('cells', models.IntegerField()),
                ('samples', models.IntegerField()),
                ('platform', models.CharField(max_length=100)),
                ('abstract', models.TextField(default='')),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='cell_atlas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_type', models.CharField(max_length=100)),
                ('gene', models.CharField(max_length=100)),
                ('avg_log2FC', models.FloatField()),
                ('pct_1', models.FloatField()),
                ('pct_2', models.FloatField()),
                ('p_value', models.FloatField()),
                ('p_val_adj', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
